import { cors, json, svc } from "../_shared/aa.ts";
import { STAFF_ROLES } from "../_shared/ai-asset-generation.ts";
import { resolveImageConfiguration, safeGenerationError, submitAiBackgroundBatch } from "../_shared/ai-background-image.ts";
const FUNCTION_NAME="generate-ai-background-image";
const fail=(status:number,stage:string,message:string)=>json({ok:false,function:FUNCTION_NAME,stage,message},status);
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return fail(405,"request","POST only");const sb=svc();let generationId="";try{
  const jwt=(req.headers.get("Authorization")??"").replace(/^Bearer\s+/i,"");const{data:{user},error:userError}=await sb.auth.getUser(jwt);if(userError||!user)return fail(401,"authorization","Not authenticated.");const{data:operator}=await sb.from("users").select("role").eq("id",user.id).maybeSingle();if(!operator||!STAFF_ROLES.has(operator.role))return fail(403,"authorization","Staff role required.");
  const body=await req.json() as {generation_id?:string;client_id?:string;image_size?:string;image_quality?:string};generationId=body.generation_id?.trim()??"";const clientId=body.client_id?.trim()??"";if(!generationId||!clientId)return fail(400,"request","generation_id and client_id are required.");const apiKey=(Deno.env.get("OPENAI_API_KEY")??"").trim();if(!apiKey)return fail(503,"configuration","OPENAI_API_KEY is not configured.");
  const config=resolveImageConfiguration({model:Deno.env.get("OPENAI_IMAGE_MODEL"),defaultSize:Deno.env.get("OPENAI_IMAGE_SIZE_DEFAULT"),defaultQuality:Deno.env.get("OPENAI_IMAGE_QUALITY_DEFAULT"),requestedSize:body.image_size,requestedQuality:body.image_quality});
  const{data,error}=await sb.rpc("generate_ai_background_image",{p_generation_id:generationId,p_client_id:clientId,p_image_size:config.size,p_image_quality:config.quality});if(error)throw error;const claim=data?.[0];if(!claim)throw new Error("Generation claim was rejected.");console.info(JSON.stringify({function:FUNCTION_NAME,stage:"batch_submit_started",generation_id:generationId}));
  try{const submitted=await submitAiBackgroundBatch({fetchImpl:fetch,apiKey,generationId,prompt:claim.prompt_text,config});const now=new Date().toISOString();const saved=await sb.from("client_ai_background_image_generations").update({prompt_status:"provider_submitted",provider_request_id:submitted.batchId,provider_input_file_id:submitted.inputFileId,provider_status:submitted.status,provider_submitted_at:now,provider_expires_at:submitted.expiresAt,image_model:config.model,image_size:config.size,image_quality:config.quality,error_message:null,last_provider_error:null,updated_at:now}).eq("id",generationId).eq("prompt_status","generating").select("*").single();if(saved.error||!saved.data)throw new Error(saved.error?.message??"Could not persist provider submission.");console.info(JSON.stringify({function:FUNCTION_NAME,stage:"provider_submitted",generation_id:generationId}));return json({ok:true,generation:saved.data});}
  catch(error){const message=safeGenerationError(error);await sb.from("client_ai_background_image_generations").update({prompt_status:"failed",error_message:message,last_provider_error:message,updated_at:new Date().toISOString()}).eq("id",generationId).eq("prompt_status","generating");throw error;}
}catch(error){const message=safeGenerationError(error);console.info(JSON.stringify({function:FUNCTION_NAME,stage:"terminal_error",generation_id:generationId||null}));return fail(500,"submit",message);}});
