// Reel Studio initial-image prompt compiler.
//
// Every still is generated by an independent text-to-image call, so the image
// model has no memory of the previous shot. Asking the language model to
// "remember to repeat the brand and continuity details in each prompt" is not a
// guarantee — it is a hope. This compiler makes it structural: the model
// supplies only shot-specific direction, and the global visual bible, the
// sequence continuity anchors, and the negative constraints are appended here
// for every shot, identically.
//
// The compiled string is what `submit-shot-still-image` sends to the provider,
// and it stays a plain editable field afterwards: an operator edit to
// `compiled_prompt` is preserved verbatim and is what actually gets generated.

import type { ContractResult } from "./reel-studio-contract.ts";
import type { ReelContinuityPlan } from "./reel-studio-story-contract.ts";

export const PROMPT_COMPILER_VERSION = "reel-prompt-compiler@1.0.0";

/** Upper bound on a compiled prompt. Beyond this, image models reweight badly. */
export const MAX_COMPILED_PROMPT_CHARS = 2000;

/**
 * Per-field cap on continuity-bible text. A model that writes a 600-character
 * `location_bible` must not be able to crowd the palette and lens out of every
 * prompt in the sequence.
 */
const MAX_BIBLE_FIELD_CHARS = 220;

export interface ReelShotDirection {
  subject: string;
  action: string;
  composition: string;
  camera_angle: string;
  depth_and_focus: string;
  lighting: string;
  visual_metaphor: string;
}

export interface CompilePromptInput {
  direction: ReelShotDirection;
  continuity: ReelContinuityPlan;
  /** Continuity anchors this specific shot must carry from the sequence. */
  shotContinuity: string[];
  humanPresence: "none" | "hands_only";
  /** Brand negative requirements, merged with the global negative prompt. */
  brandNegative: string | null;
}

function record(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function text(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

const DIRECTION_FIELDS: Array<keyof ReelShotDirection> = [
  "subject",
  "action",
  "composition",
  "camera_angle",
  "depth_and_focus",
  "lighting",
  "visual_metaphor",
];

export function validateShotDirection(value: unknown): ContractResult<ReelShotDirection> {
  const input = record(value);
  if (!input) return { ok: false, error: "shot_direction must be a JSON object." };
  const direction: Record<string, string> = {};
  for (const field of DIRECTION_FIELDS) {
    const entry = text(input[field]);
    if (!entry) return { ok: false, error: `shot_direction.${field} must be a non-empty string.` };
    direction[field] = entry;
  }
  return { ok: true, value: direction as unknown as ReelShotDirection };
}

/**
 * Constraints that always apply to this faceless 9:16 format, regardless of
 * what the model wrote. Kept short — image models dilute long negative lists.
 */
const STRUCTURAL_NEGATIVES = [
  "no readable text, captions, watermarks, subtitles or UI overlays",
  "no logos or brand marks",
  "no distorted or extra fingers",
  "no additional people entering frame",
  "no style drift from the stated grade and lens",
  "no conflicting camera directions",
];

function dedupePhrases(phrases: string[]): string[] {
  const seen = new Set<string>();
  const output: string[] = [];
  for (const phrase of phrases) {
    const clean = phrase.trim().replace(/[.;]+$/, "");
    if (!clean) continue;
    const key = clean.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    output.push(clean);
  }
  return output;
}

/**
 * Negative lists arrive from three sources (structural, brand, continuity plan)
 * that routinely restate each other — "no faces, no fake signage…" appearing
 * almost verbatim in two of them. Exact-match dedupe does not catch that, so
 * negatives are split into individual constraints and deduped per constraint.
 * This recovers prompt weight that near-duplicates would otherwise waste.
 */
function mergeNegatives(sources: string[]): string[] {
  const seen = new Set<string>();
  const merged: string[] = [];
  for (const source of sources) {
    for (const raw of source.split(/[;,]/)) {
      const clean = raw.trim().replace(/^[.\s]+|[.\s]+$/g, "");
      if (!clean) continue;
      // Normalise so "No faces" and "no faces" collapse to one constraint.
      const key = clean.toLowerCase().replace(/^no\s+/, "").replace(/\s+/g, " ");
      if (seen.has(key)) continue;
      seen.add(key);
      merged.push(clean.toLowerCase().startsWith("no ") ? clean : `no ${clean}`);
    }
  }
  return merged;
}

/**
 * Bound one bible field so a verbose plan cannot dominate every prompt.
 *
 * Cuts at a sentence boundary where possible, and otherwise at a clause
 * boundary — never mid-clause. Trailing conjunctions and copulas are stripped
 * so the result cannot end on a dangling fragment like "…highlights are",
 * which reads to an image model as an unfinished instruction.
 */
function bounded(value: string): string {
  const clean = value.trim();
  if (clean.length <= MAX_BIBLE_FIELD_CHARS) return clean;

  const window = clean.slice(0, MAX_BIBLE_FIELD_CHARS);
  const sentence = Math.max(window.lastIndexOf(". "), window.lastIndexOf("; "));
  const cut = sentence > MAX_BIBLE_FIELD_CHARS * 0.4
    ? window.slice(0, sentence)
    : window.slice(0, Math.max(window.lastIndexOf(", "), window.lastIndexOf(" ")));

  // Drop a trailing dangling word so the clause reads as complete.
  return cut
    .replace(/[\s,;:—-]+$/, "")
    .replace(/\s+(?:and|or|but|with|the|a|an|is|are|was|were|of|to|in|on|for|as|that|which|while)$/i, "")
    .trim();
}

/**
 * Assemble the prompt within budget.
 *
 * `protectedClauses` are the global visual bible — palette, lens, lighting,
 * continuity anchors, human presence, aspect ratio. They are what makes six
 * independent image calls look like one sequence, so they are never dropped;
 * only `optional` clauses are shed, from the end, when the budget is tight.
 *
 * Getting this order wrong is not a cosmetic bug: an earlier version listed the
 * palette and lens last, so trimming silently removed exactly the context the
 * compiler exists to guarantee.
 */
function fitClauses(
  head: string,
  protectedClauses: string[],
  optional: string[],
  tail: string,
  limit: number,
): string {
  let kept = [...optional];
  while (kept.length > 0) {
    const candidate = [head, ...kept, ...protectedClauses, tail].filter(Boolean).join(" ");
    if (candidate.length <= limit) return candidate;
    kept = kept.slice(0, -1);
  }
  // Head + bible + negatives only. If that still exceeds the budget the bible
  // is kept anyway — an over-long prompt degrades gracefully, a prompt missing
  // its continuity does not.
  return [head, ...protectedClauses, tail].filter(Boolean).join(" ");
}

/**
 * Compile one production-ready image instruction.
 *
 * Order matters: subject and action lead (image models weight early tokens
 * most), then composition and camera, then the world/continuity anchors that
 * hold the sequence together, then the grade/lens/mood bible, then negatives.
 */
export function compileShotPrompt(input: CompilePromptInput): string {
  const d = input.direction;
  const c = input.continuity;

  const humanClause = input.humanPresence === "hands_only"
    ? "Only hands are visible; no face and no full figure in frame."
    : "No people, no faces and no body parts in frame.";

  const head = [
    `${d.subject}, ${d.action}.`,
    `${d.composition}, ${d.camera_angle}.`,
  ].join(" ");

  const continuityAnchors = dedupePhrases([
    ...input.shotContinuity,
    ...c.recurring_objects,
  ]).slice(0, 6).map(bounded);

  const punctuate = (clauses: string[]) =>
    dedupePhrases(clauses).map((clause) => (clause.endsWith(".") ? clause : `${clause}.`));

  // Never dropped: this is the sequence's visual identity.
  const protectedClauses = punctuate([
    `Recurring elements that must stay identical across every shot: ${continuityAnchors.join("; ")}`,
    `Palette: ${bounded(c.palette_bible)}`,
    `Lighting bible: ${bounded(c.lighting_bible)}`,
    `Lens: ${bounded(c.lens_bible)}`,
    humanClause,
    "Vertical 9:16 frame, photographic, cinematic production quality.",
  ]);

  // Shed from the end when the budget is tight, least load-bearing last.
  const optional = punctuate([
    d.depth_and_focus,
    d.lighting,
    `Visual idea: ${d.visual_metaphor}`,
    `World: ${bounded(c.visual_world)}`,
    `Location: ${bounded(c.location_bible)}`,
    `Subject treatment: ${bounded(c.subject_bible)}`,
    `Screen direction: ${bounded(c.screen_direction)}`,
    ...c.continuity_constraints.slice(0, 3).map(bounded),
  ]);

  const negatives = mergeNegatives([
    ...STRUCTURAL_NEGATIVES,
    ...(input.brandNegative ? [input.brandNegative] : []),
    c.global_negative_prompt,
  ]);
  const tail = `Avoid: ${negatives.join("; ")}.`;

  return fitClauses(head, protectedClauses, optional, tail, MAX_COMPILED_PROMPT_CHARS);
}

/**
 * Assertions the compiler's own output must satisfy. Used by tests and by the
 * generator as a defence-in-depth check before anything is persisted.
 */
export function compiledPromptCarriesGlobalContext(
  prompt: string,
  continuity: ReelContinuityPlan,
): boolean {
  const lower = prompt.toLowerCase();
  return (
    lower.includes("avoid:") &&
    lower.includes("9:16") &&
    (lower.includes(continuity.palette_bible.toLowerCase().slice(0, 18)) ||
      lower.includes("palette:")) &&
    (lower.includes("lens:") || lower.includes(continuity.lens_bible.toLowerCase().slice(0, 18)))
  );
}
