alter table public.client_ai_background_image_generations drop constraint if exists client_ai_background_image_generations_prompt_status_check;
alter table public.client_ai_background_image_generations add constraint client_ai_background_image_generations_prompt_status_check check (prompt_status in ('draft','needs_review','approved','rejected','generating','provider_submitted','checking','generated','failed'));
alter table public.client_ai_background_image_generations add column provider_request_id text, add column provider_input_file_id text, add column provider_status text, add column provider_submitted_at timestamptz, add column provider_checked_at timestamptz, add column provider_completed_at timestamptz, add column provider_expires_at timestamptz, add column last_provider_error text, add column check_count integer not null default 0 check(check_count>=0);
create unique index client_ai_background_provider_request_unique on public.client_ai_background_image_generations(provider_request_id) where provider_request_id is not null;
create or replace function public.recover_stale_ai_background_generation(p_generation_id uuid) returns public.client_ai_background_image_generations language plpgsql security definer set search_path='' as $$ declare v_row public.client_ai_background_image_generations; v_message constant text := 'Recovered after interrupted provider execution; no image was stored. Create a new prompt/generation if retry is required.'; begin
if auth.role()<>'service_role' and (auth.uid() is null or coalesce(public.auth_role(),'') not in ('admin','account_manager','editor')) then raise exception 'AUTH: staff role required'; end if;
update public.client_ai_background_image_generations set prompt_status='failed',error_message=v_message,last_provider_error=v_message,updated_at=now() where id=p_generation_id and prompt_status in ('generating','provider_submitted','checking') and storage_path is null and generated_at is null and provider_response='{}'::jsonb and updated_at<now()-interval '5 minutes' returning * into v_row;
if not found then raise exception 'RECOVERY_REJECTED: generation must be stale and have no stored or provider result'; end if;
insert into public.activity_log(client_id,event_type,plain_english_message,object_type,object_id,metadata) values(v_row.client_id,'ai_background_generation_recovered','Interrupted AI background generation recovered as failed for '||v_row.source_ref||'.','client_ai_background_image_generation',v_row.id,jsonb_build_object('source_ref',v_row.source_ref,'new_status','failed'));
return v_row; end $$;
revoke all on function public.recover_stale_ai_background_generation(uuid) from public,anon; grant execute on function public.recover_stale_ai_background_generation(uuid) to authenticated,service_role;
