-- ============================================================
-- RECOVERED 2026-08-06 from supabase_migrations.schema_migrations
-- on project xivewedajschthjlblfb.
--
-- This file was previously a 14-line comment stub containing NO SQL. The
-- migration had been applied via the Supabase MCP tool on 2026-07-02 and its
-- statements were never captured into the repository. Consequences while the
-- stub stood:
--   * `supabase db reset` could not rebuild the database at all — the base
--     schema (17 enums, 31 tables, RLS, seed data) existed only in production.
--   * auth_role() and auth_client_ids() had no definition in version control,
--     while 37 later migrations reference them.
--
-- The body below is the statements column verbatim, exactly as applied.
--   md5    94aa19dbe0b497c58528956bd6a42d9a
--   length 54,967 characters
--
-- Do NOT edit this file in place. Correct anything here with an additive
-- migration, per the project's migration discipline.
-- ============================================================

-- ============================================================
-- V1 Foundation — Attract Acquisition Cockpit — 2026-07-02
-- Order: enums → tables → triggers → functions → views → indexes → RLS → seed
-- ============================================================

-- ============================================================
-- ENUMS
-- ============================================================
CREATE TYPE public.user_role          AS ENUM ('admin', 'account_manager', 'editor', 'client');
CREATE TYPE public.package_tier       AS ENUM ('proof_sprint', 'proof_brand', 'proof_brand_scale');
CREATE TYPE public.client_status      AS ENUM ('prospect', 'active', 'paused', 'churned');
CREATE TYPE public.stage_status       AS ENUM ('not_run', 'running', 'complete', 'error');
CREATE TYPE public.review_state       AS ENUM ('needs_review', 'approved', 'rejected', 'archived');
CREATE TYPE public.context_file_status AS ENUM ('not_started', 'generating', 'generated', 'needs_review', 'approved', 'needs_client_input');
CREATE TYPE public.source_ref_type    AS ENUM ('organic', 'story', 'ad', 'sales', 'design', 'lead_magnet', 'website');
CREATE TYPE public.production_status  AS ENUM ('not_started', 'brief_ready', 'in_production', 'in_review', 'approved', 'delivered', 'killed');
CREATE TYPE public.organic_status     AS ENUM ('idea', 'briefed', 'filming', 'editing', 'scheduled', 'live', 'repurposed', 'killed');
CREATE TYPE public.ad_status          AS ENUM ('planned', 'building', 'live', 'paused', 'done', 'killed', 'deferred');
CREATE TYPE public.proof_status       AS ENUM ('missing', 'requested', 'captured', 'verified', 'approved', 'in_use', 'archived');
CREATE TYPE public.automation_type    AS ENUM ('marketing_intelligence', 'creative_intelligence', 'story_intelligence', 'distribution', 'opportunity_detector', 'ai_receptionist');
CREATE TYPE public.pipeline_source    AS ENUM ('manual', 'api', 'ai_assisted');
CREATE TYPE public.calendar_row_type  AS ENUM ('ad1', 'ad2', 'ad3', 'reel', 'stories', 'feed_posts', 'carousels');
CREATE TYPE public.playbook_run_status  AS ENUM ('running', 'proposed', 'approved', 'rejected', 'error');
CREATE TYPE public.automation_run_status AS ENUM ('running', 'success', 'error', 'cancelled');
CREATE TYPE public.integration_status AS ENUM ('not_configured', 'configured', 'error');

-- ============================================================
-- UPDATED_AT TRIGGER FUNCTION
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE public.users (
  id         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email      TEXT NOT NULL,
  full_name  TEXT,
  role       public.user_role NOT NULL DEFAULT 'account_manager',
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER users_updated_at BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE PLPGSQL SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- WORKSPACES
-- ============================================================
CREATE TABLE public.workspaces (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL DEFAULT 'Attract Acquisition',
  slug       TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER workspaces_updated_at BEFORE UPDATE ON public.workspaces
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- CLIENTS
-- ============================================================
CREATE TABLE public.clients (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT NOT NULL,
  slug                TEXT NOT NULL UNIQUE,
  is_internal_client  BOOLEAN NOT NULL DEFAULT FALSE,
  package_tier        public.package_tier NOT NULL DEFAULT 'proof_sprint',
  status              public.client_status NOT NULL DEFAULT 'prospect',
  account_manager_id  UUID REFERENCES public.users(id),
  geography           TEXT,
  primary_platform    TEXT,
  secondary_platform  TEXT,
  stage1_status       public.stage_status NOT NULL DEFAULT 'not_run',
  stage1_completed_at TIMESTAMPTZ,
  stage2_status       public.stage_status NOT NULL DEFAULT 'not_run',
  stage2_completed_at TIMESTAMPTZ,
  health_score        INT DEFAULT 0 CHECK (health_score >= 0 AND health_score <= 100),
  health_updated_at   TIMESTAMPTZ,
  package_config      JSONB DEFAULT '{}',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER clients_updated_at BEFORE UPDATE ON public.clients
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- TEAM MEMBERS / CLIENT USERS
-- ============================================================
CREATE TABLE public.team_members (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id   UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, client_id)
);
CREATE TABLE public.client_users (
  id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id   UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, client_id)
);

-- ============================================================
-- AUTH HELPERS (PL/pgSQL — validated at runtime, not parse time)
-- ============================================================
CREATE OR REPLACE FUNCTION public.auth_role()
RETURNS TEXT LANGUAGE PLPGSQL STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN (SELECT role::text FROM public.users WHERE id = auth.uid());
END;
$$;

CREATE OR REPLACE FUNCTION public.auth_client_ids()
RETURNS UUID[] LANGUAGE PLPGSQL STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_role TEXT;
BEGIN
  v_role := public.auth_role();
  RETURN CASE v_role
    WHEN 'admin'           THEN ARRAY(SELECT id FROM public.clients)
    WHEN 'account_manager' THEN ARRAY(SELECT client_id FROM public.team_members WHERE user_id = auth.uid())
    WHEN 'client'          THEN ARRAY(SELECT client_id FROM public.client_users WHERE user_id = auth.uid())
    ELSE ARRAY[]::uuid[]
  END;
END;
$$;

-- ============================================================
-- CLIENT INPUTS
-- ============================================================
CREATE TABLE public.client_inputs (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id            UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE UNIQUE,
  business_description TEXT,
  website_url          TEXT,
  social_links         JSONB DEFAULT '{}',
  offer_details        TEXT,
  target_customer      TEXT,
  geography            TEXT,
  proof_notes          TEXT,
  testimonials_notes   TEXT,
  reviews_notes        TEXT,
  case_studies_notes   TEXT,
  before_after_notes   TEXT,
  founder_team_notes   TEXT,
  current_problems     TEXT,
  uploaded_file_refs   JSONB DEFAULT '[]',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER client_inputs_updated_at BEFORE UPDATE ON public.client_inputs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- QUALIFICATION CONFIGS
-- ============================================================
CREATE TABLE public.qualification_configs (
  id                           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                    UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE UNIQUE,
  qualified_follower_rules     TEXT,
  qualified_conversation_rules TEXT,
  qualified_appointment_rules  TEXT,
  additional_config            JSONB DEFAULT '{}',
  updated_by                   UUID REFERENCES public.users(id),
  created_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER qualification_configs_updated_at BEFORE UPDATE ON public.qualification_configs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- CLIENT CONTEXT FILES (21 Stage 1 files)
-- ============================================================
CREATE TABLE public.client_context_files (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  file_number           INT NOT NULL CHECK (file_number >= 0 AND file_number <= 20),
  file_name             TEXT NOT NULL,
  content_md            TEXT,
  storage_path          TEXT,
  status                public.context_file_status NOT NULL DEFAULT 'not_started',
  confidence_level      TEXT,
  generated_by_function TEXT,
  version               INT NOT NULL DEFAULT 1,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, file_number)
);
CREATE TRIGGER client_context_files_updated_at BEFORE UPDATE ON public.client_context_files
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- CLIENT EXECUTION FILES (Stage 2 pack — narrative docs)
-- ============================================================
CREATE TABLE public.client_execution_files (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                 TEXT NOT NULL,
  file_name             TEXT NOT NULL,
  file_number           INT,
  file_type             TEXT,
  content_md            TEXT,
  storage_bucket        TEXT,
  storage_path          TEXT,
  status                TEXT,
  version               INT NOT NULL DEFAULT 1,
  generated_by_agent    TEXT,
  generated_by_function TEXT,
  reviewed_by           UUID REFERENCES public.users(id),
  approved_by           UUID REFERENCES public.users(id),
  approved_at           TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, month, file_name)
);
CREATE TRIGGER client_execution_files_updated_at BEFORE UPDATE ON public.client_execution_files
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ORGANIC MASTER
-- ============================================================
CREATE TABLE public.organic_master (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id            UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                TEXT NOT NULL,
  ref                  TEXT NOT NULL,
  review_state         public.review_state NOT NULL DEFAULT 'needs_review',
  status               public.organic_status NOT NULL DEFAULT 'idea',
  content_type         TEXT NOT NULL CHECK (content_type IN ('RL', 'FP', 'CR')),
  archetype            TEXT,
  pillar               TEXT,
  working_title        TEXT,
  the_one_person       TEXT,
  one_belief_to_change TEXT,
  hook                 TEXT,
  core_message         TEXT,
  cta                  TEXT,
  storyboard_outline   TEXT,
  caption_script       TEXT,
  source_origin        TEXT,
  distribution_date    DATE,
  distribution_channel TEXT,
  production_date      DATE,
  edit_date            DATE,
  production_brief     TEXT,
  editor               UUID REFERENCES public.users(id),
  psychological_angle  TEXT,
  repurposed_from_to   TEXT,
  format_proven        BOOLEAN,
  notes                TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER organic_master_updated_at BEFORE UPDATE ON public.organic_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- STORY MASTER
-- ============================================================
CREATE TABLE public.story_master (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                 TEXT NOT NULL,
  ref                   TEXT NOT NULL,
  review_state          public.review_state NOT NULL DEFAULT 'needs_review',
  status                public.organic_status NOT NULL DEFAULT 'idea',
  story_theme           TEXT,
  pillar                TEXT,
  frame_1               TEXT,
  frame_2               TEXT,
  frame_3               TEXT,
  frame_4_optional      TEXT,
  cta_engagement_prompt TEXT,
  proof_used            TEXT,
  source_origin         TEXT,
  distribution_date     DATE,
  repurposed_from_to    TEXT,
  what_not_to_claim     TEXT,
  notes                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER story_master_updated_at BEFORE UPDATE ON public.story_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ADS MASTER
-- ============================================================
CREATE TABLE public.ads_master (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id         UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month             TEXT NOT NULL,
  ref               TEXT NOT NULL,
  review_state      public.review_state NOT NULL DEFAULT 'needs_review',
  status            public.ad_status NOT NULL DEFAULT 'planned',
  lane              TEXT NOT NULL CHECK (lane IN ('Ad 1', 'Ad 2', 'Ad 3')),
  stint_name        TEXT,
  objective         TEXT,
  funnel_stage      TEXT,
  start_date        DATE,
  end_date          DATE,
  days              INT,
  budget_split      TEXT,
  primary_goal      TEXT,
  conversion_action TEXT,
  meta_objective    TEXT,
  audience          TEXT,
  creative_source   TEXT,
  hook_angle        TEXT,
  kpi_watch         TEXT,
  feeds_into        TEXT,
  notes             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER ads_master_updated_at BEFORE UPDATE ON public.ads_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- AD CREATIVE (child of ads_master)
-- ============================================================
CREATE TABLE public.ad_creative (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id            UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  parent_ad_ref        TEXT NOT NULL,
  creative_id          TEXT NOT NULL,
  creative_source_type TEXT CHECK (creative_source_type IN ('organic', 'uploaded', 'generated', 'proof')),
  creative_source_ref  TEXT,
  hook_angle           TEXT,
  format               TEXT,
  status               TEXT,
  spend                NUMERIC(12,2),
  impressions          INT,
  clicks               INT,
  leads                INT,
  conversations        INT,
  cpl                  NUMERIC(12,2),
  notes                TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER ad_creative_updated_at BEFORE UPDATE ON public.ad_creative
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- PROOF MASTER
-- ============================================================
CREATE TABLE public.proof_master (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id              UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                  TEXT,
  ref                    TEXT NOT NULL,
  review_state           public.review_state NOT NULL DEFAULT 'needs_review',
  proof_type             TEXT,
  proof_asset_name       TEXT,
  source                 TEXT,
  status                 public.proof_status NOT NULL DEFAULT 'missing',
  consent_status         TEXT,
  claim_status           TEXT,
  strength_rating        TEXT,
  proof_gap_addressed    TEXT,
  where_can_be_used      TEXT,
  where_must_not_be_used TEXT,
  owner                  UUID REFERENCES public.users(id),
  capture_date           DATE,
  downstream_refs        JSONB DEFAULT '[]',
  notes                  TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER proof_master_updated_at BEFORE UPDATE ON public.proof_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ASSET MASTER
-- ============================================================
CREATE TABLE public.asset_master (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id       UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  asset_id        TEXT NOT NULL,
  source          TEXT,
  uploader        UUID REFERENCES public.users(id),
  file_path       TEXT,
  storage_bucket  TEXT,
  asset_type      TEXT,
  linked_ref      TEXT,
  linked_proof_id TEXT,
  status          TEXT,
  approval_status TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, asset_id)
);
CREATE TRIGGER asset_master_updated_at BEFORE UPDATE ON public.asset_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- LEAD MAGNET MASTER
-- ============================================================
CREATE TABLE public.lead_magnet_master (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id              UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                  TEXT,
  ref                    TEXT NOT NULL,
  review_state           public.review_state NOT NULL DEFAULT 'needs_review',
  concept                TEXT,
  landing_page_copy      TEXT,
  nurture_emails         TEXT,
  ad_angles              TEXT,
  delivery_asset_outline TEXT,
  status                 TEXT,
  linked_proof           TEXT,
  linked_offer           TEXT,
  cta                    TEXT,
  destination            TEXT,
  notes                  TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER lead_magnet_master_updated_at BEFORE UPDATE ON public.lead_magnet_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- WEBSITE MASTER
-- ============================================================
CREATE TABLE public.website_master (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id              UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month                  TEXT,
  ref                    TEXT NOT NULL,
  review_state           public.review_state NOT NULL DEFAULT 'needs_review',
  page_section           TEXT,
  role                   TEXT,
  message                TEXT,
  proof_required         TEXT,
  cta                    TEXT,
  section_copy_direction TEXT,
  claims_allowed         TEXT,
  status                 TEXT,
  notes                  TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, ref)
);
CREATE TRIGGER website_master_updated_at BEFORE UPDATE ON public.website_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- SOPS_LAWS
-- ============================================================
CREATE TABLE public.sops_laws (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id    UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month        TEXT,
  review_state public.review_state NOT NULL DEFAULT 'needs_review',
  content_json JSONB DEFAULT '{}',
  content_md   TEXT,
  version      INT NOT NULL DEFAULT 1,
  updated_by   UUID REFERENCES public.users(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER sops_laws_updated_at BEFORE UPDATE ON public.sops_laws
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- WEEKLY SEQUENCE
-- ============================================================
CREATE TABLE public.weekly_sequence (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id           UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  review_state        public.review_state NOT NULL DEFAULT 'needs_review',
  day_of_week         TEXT NOT NULL,
  slot_time           TEXT,
  content_type        TEXT,
  archetype_lean      TEXT,
  rationale           TEXT,
  production_note     TEXT,
  tally               TEXT,
  non_negotiable_flag BOOLEAN DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER weekly_sequence_updated_at BEFORE UPDATE ON public.weekly_sequence
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ASSET BRIEF INDEX
-- ============================================================
CREATE TABLE public.asset_brief_index (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  execution_month       TEXT NOT NULL,
  brief_id              TEXT NOT NULL,
  source_ref            TEXT NOT NULL,
  source_ref_type       public.source_ref_type NOT NULL,
  asset_type            TEXT,
  platform              TEXT,
  required_source_files JSONB DEFAULT '[]',
  required_proof_ids    JSONB DEFAULT '[]',
  cta                   TEXT,
  production_status     public.production_status NOT NULL DEFAULT 'not_started',
  review_requirement    BOOLEAN NOT NULL DEFAULT TRUE,
  owner_user_id         UUID REFERENCES public.users(id),
  notes                 TEXT,
  status                public.review_state NOT NULL DEFAULT 'needs_review',
  created_by            UUID REFERENCES public.users(id),
  approved_by           UUID REFERENCES public.users(id),
  approved_at           TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, brief_id)
);
CREATE TRIGGER asset_brief_index_updated_at BEFORE UPDATE ON public.asset_brief_index
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- CALENDAR CELLS
-- ============================================================
CREATE TABLE public.calendar_cells (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id    UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month        TEXT NOT NULL,
  date         DATE NOT NULL,
  row_type     public.calendar_row_type NOT NULL,
  ref          TEXT NOT NULL,
  review_state public.review_state NOT NULL DEFAULT 'approved',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, date, row_type, ref)
);
CREATE TRIGGER calendar_cells_updated_at BEFORE UPDATE ON public.calendar_cells
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- PIPELINE METRICS DAILY
-- ============================================================
CREATE TABLE public.pipeline_metrics_daily (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id               UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  date                    DATE NOT NULL,
  profile_visits          INT DEFAULT 0,
  followers               INT DEFAULT 0,
  qualified_followers     INT DEFAULT 0,
  conversations           INT DEFAULT 0,
  qualified_conversations INT DEFAULT 0,
  appointments            INT DEFAULT 0,
  qualified_appointments  INT DEFAULT 0,
  show_ups                INT DEFAULT 0,
  cash_collected          NUMERIC(12,2) DEFAULT 0,
  source                  public.pipeline_source NOT NULL DEFAULT 'manual',
  notes                   TEXT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (client_id, date)
);
CREATE TRIGGER pipeline_metrics_daily_updated_at BEFORE UPDATE ON public.pipeline_metrics_daily
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- PLAYBOOKS (Stage 0 registry)
-- ============================================================
CREATE TABLE public.playbooks (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  type         TEXT,
  storage_path TEXT,
  content_md   TEXT,
  version      INT NOT NULL DEFAULT 1,
  status       TEXT NOT NULL DEFAULT 'active',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER playbooks_updated_at BEFORE UPDATE ON public.playbooks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- PLAYBOOK RUNS
-- ============================================================
CREATE TABLE public.playbook_runs (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id               UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  playbook_slug           TEXT NOT NULL,
  month                   TEXT,
  status                  public.playbook_run_status NOT NULL DEFAULT 'running',
  input_context_refs      JSONB DEFAULT '[]',
  reasoning_summary       TEXT,
  proposed_output         JSONB,
  affected_tables         JSONB DEFAULT '[]',
  affected_calendar_dates JSONB DEFAULT '[]',
  risks                   JSONB DEFAULT '[]',
  run_by                  UUID REFERENCES public.users(id),
  decided_at              TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER playbook_runs_updated_at BEFORE UPDATE ON public.playbook_runs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- AUTOMATIONS
-- ============================================================
CREATE TABLE public.automations (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  automation_type       public.automation_type NOT NULL,
  enabled               BOOLEAN NOT NULL DEFAULT FALSE,
  required_secret_names JSONB DEFAULT '[]',
  configured            BOOLEAN NOT NULL DEFAULT FALSE,
  schedule_cron         TEXT,
  last_run_at           TIMESTAMPTZ,
  next_run_at           TIMESTAMPTZ,
  status                TEXT DEFAULT 'idle',
  last_error            TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER automations_updated_at BEFORE UPDATE ON public.automations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- AUTOMATION RUNS
-- ============================================================
CREATE TABLE public.automation_runs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  automation_id UUID NOT NULL REFERENCES public.automations(id) ON DELETE CASCADE,
  client_id     UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  run_type      TEXT NOT NULL DEFAULT 'manual',
  status        public.automation_run_status NOT NULL DEFAULT 'running',
  input         JSONB DEFAULT '{}',
  output        JSONB DEFAULT '{}',
  error_message TEXT,
  started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ
);

-- ============================================================
-- INTEGRATIONS
-- ============================================================
CREATE TABLE public.integrations (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT NOT NULL UNIQUE,
  status     public.integration_status NOT NULL DEFAULT 'not_configured',
  notes      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER integrations_updated_at BEFORE UPDATE ON public.integrations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- SECRET REFERENCES (names only — never values)
-- ============================================================
CREATE TABLE public.secret_references (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  secret_name    TEXT NOT NULL UNIQUE,
  integration_id UUID REFERENCES public.integrations(id),
  present        BOOLEAN NOT NULL DEFAULT FALSE,
  added_by       UUID REFERENCES public.users(id),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER secret_references_updated_at BEFORE UPDATE ON public.secret_references
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ACTIVITY LOG
-- ============================================================
CREATE TABLE public.activity_log (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id             UUID REFERENCES public.clients(id) ON DELETE SET NULL,
  actor_id              UUID REFERENCES public.users(id) ON DELETE SET NULL,
  event_type            TEXT NOT NULL,
  plain_english_message TEXT NOT NULL,
  object_type           TEXT,
  object_id             TEXT,
  metadata              JSONB DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- AUDIT LOG
-- ============================================================
CREATE TABLE public.audit_log (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id   UUID REFERENCES public.users(id) ON DELETE SET NULL,
  table_name TEXT NOT NULL,
  record_id  TEXT,
  action     TEXT NOT NULL,
  old_data   JSONB,
  new_data   JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- REF COUNTERS + generate_ref
-- ============================================================
CREATE TABLE public.ref_counters (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id     UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  month         TEXT NOT NULL,
  channel       TEXT NOT NULL,
  current_count INT NOT NULL DEFAULT 0,
  UNIQUE (client_id, month, channel)
);

CREATE OR REPLACE FUNCTION public.generate_ref(
  p_client_id  UUID,
  p_month_code TEXT,
  p_channel    TEXT
)
RETURNS TEXT LANGUAGE PLPGSQL SECURITY DEFINER SET search_path = public AS $$
DECLARE v_count INT;
BEGIN
  INSERT INTO public.ref_counters (client_id, month, channel, current_count)
  VALUES (p_client_id, p_month_code, p_channel, 1)
  ON CONFLICT (client_id, month, channel)
  DO UPDATE SET current_count = ref_counters.current_count + 1
  RETURNING current_count INTO v_count;
  RETURN p_month_code || '-' || p_channel || '-' || LPAD(v_count::text, 3, '0');
END;
$$;

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_clients_acct_mgr       ON public.clients(account_manager_id);
CREATE INDEX idx_clients_status         ON public.clients(status);
CREATE INDEX idx_clients_stage1         ON public.clients(stage1_status);
CREATE INDEX idx_clients_stage2         ON public.clients(stage2_status);
CREATE INDEX idx_team_members_user      ON public.team_members(user_id);
CREATE INDEX idx_team_members_client    ON public.team_members(client_id);
CREATE INDEX idx_client_users_user      ON public.client_users(user_id);
CREATE INDEX idx_ccf_client             ON public.client_context_files(client_id);
CREATE INDEX idx_cef_client_month       ON public.client_execution_files(client_id, month);
CREATE INDEX idx_organic_client_month   ON public.organic_master(client_id, month);
CREATE INDEX idx_organic_review         ON public.organic_master(review_state);
CREATE INDEX idx_organic_dist_date      ON public.organic_master(distribution_date);
CREATE INDEX idx_story_client_month     ON public.story_master(client_id, month);
CREATE INDEX idx_story_dist_date        ON public.story_master(distribution_date);
CREATE INDEX idx_ads_client_month       ON public.ads_master(client_id, month);
CREATE INDEX idx_ads_dates              ON public.ads_master(start_date, end_date);
CREATE INDEX idx_proof_client           ON public.proof_master(client_id);
CREATE INDEX idx_abi_client_month       ON public.asset_brief_index(client_id, execution_month);
CREATE INDEX idx_abi_status             ON public.asset_brief_index(status);
CREATE INDEX idx_calendar_client_month  ON public.calendar_cells(client_id, month);
CREATE INDEX idx_calendar_date          ON public.calendar_cells(date);
CREATE INDEX idx_pipeline_client_date   ON public.pipeline_metrics_daily(client_id, date);
CREATE INDEX idx_activity_client        ON public.activity_log(client_id);
CREATE INDEX idx_activity_created       ON public.activity_log(created_at DESC);
CREATE INDEX idx_playbook_runs_client   ON public.playbook_runs(client_id);
CREATE INDEX idx_automations_client     ON public.automations(client_id);
CREATE INDEX idx_auto_runs_client       ON public.automation_runs(client_id);
CREATE INDEX idx_auto_runs_auto         ON public.automation_runs(automation_id);

-- ============================================================
-- CLIENT HEALTH VIEW
-- ============================================================
CREATE OR REPLACE VIEW public.client_health_v AS
SELECT
  c.id,
  c.name,
  c.slug,
  c.package_tier,
  c.status,
  c.stage1_status,
  c.stage2_status,
  GREATEST(0, LEAST(100,
    CASE WHEN c.stage1_status = 'complete' THEN 20 ELSE 0 END
    + CASE WHEN c.stage2_status = 'complete' THEN 20 ELSE 0 END
    + CASE WHEN EXISTS (
        SELECT 1 FROM public.calendar_cells cc
        WHERE cc.client_id = c.id AND cc.month = TO_CHAR(CURRENT_DATE, 'YYYY-MM')
      ) THEN 15 ELSE 0 END
    + CASE WHEN c.status = 'active' THEN 10 ELSE 0 END
    + CASE WHEN EXISTS (
        SELECT 1 FROM public.client_inputs ci
        WHERE ci.client_id = c.id
          AND (ci.business_description IS NOT NULL OR ci.offer_details IS NOT NULL)
      ) THEN 5 ELSE 0 END
    - LEAST(20, 5 * (
        SELECT COUNT(*) FROM (
          SELECT 1 FROM public.organic_master om WHERE om.client_id = c.id AND om.review_state = 'needs_review' AND om.created_at < NOW() - INTERVAL '48 hours'
          UNION ALL
          SELECT 1 FROM public.story_master sm WHERE sm.client_id = c.id AND sm.review_state = 'needs_review' AND sm.created_at < NOW() - INTERVAL '48 hours'
          UNION ALL
          SELECT 1 FROM public.ads_master am WHERE am.client_id = c.id AND am.review_state = 'needs_review' AND am.created_at < NOW() - INTERVAL '48 hours'
        ) overdue
      )::int)
    - LEAST(15, 5 * (SELECT COUNT(*)::int FROM public.automations a WHERE a.client_id = c.id AND a.status = 'error'))
    - LEAST(10, 5 * (SELECT COUNT(*)::int FROM public.proof_master pm WHERE pm.client_id = c.id AND pm.status = 'missing'))
  ))::int AS health_score
FROM public.clients c;

-- ============================================================
-- ROW LEVEL SECURITY — enable
-- ============================================================
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_users          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_inputs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qualification_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_context_files  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_execution_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organic_master        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_master          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_master            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_creative           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proof_master          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_master          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_magnet_master    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_master        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sops_laws             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_sequence       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_brief_index     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_cells        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_metrics_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playbooks             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.playbook_runs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automations           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_runs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integrations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.secret_references     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ref_counters          ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- USERS
CREATE POLICY "users_self_or_admin" ON public.users FOR SELECT TO authenticated USING (id = auth.uid() OR public.auth_role() = 'admin');
CREATE POLICY "users_admin_write"   ON public.users FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- WORKSPACES
CREATE POLICY "workspaces_admin" ON public.workspaces FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- CLIENTS
CREATE POLICY "clients_select" ON public.clients FOR SELECT TO authenticated USING (id = ANY(public.auth_client_ids()));
CREATE POLICY "clients_insert" ON public.clients FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "clients_update" ON public.clients FOR UPDATE TO authenticated USING (id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "clients_delete" ON public.clients FOR DELETE TO authenticated USING (public.auth_role() = 'admin');

-- TEAM MEMBERS
CREATE POLICY "team_members_select" ON public.team_members FOR SELECT TO authenticated USING (public.auth_role() = 'admin' OR user_id = auth.uid());
CREATE POLICY "team_members_admin"  ON public.team_members FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- CLIENT USERS
CREATE POLICY "client_users_select" ON public.client_users FOR SELECT TO authenticated USING (public.auth_role() = 'admin' OR user_id = auth.uid());
CREATE POLICY "client_users_admin"  ON public.client_users FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- CLIENT INPUTS
CREATE POLICY "client_inputs_select" ON public.client_inputs FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "client_inputs_insert" ON public.client_inputs FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "client_inputs_update" ON public.client_inputs FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- QUALIFICATION CONFIGS
CREATE POLICY "qual_configs_select" ON public.qualification_configs FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "qual_configs_insert" ON public.qualification_configs FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "qual_configs_update" ON public.qualification_configs FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- CONTEXT FILES
CREATE POLICY "ccf_select" ON public.client_context_files FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "ccf_insert" ON public.client_context_files FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "ccf_update" ON public.client_context_files FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- EXECUTION FILES
CREATE POLICY "cef_select" ON public.client_execution_files FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "cef_insert" ON public.client_execution_files FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "cef_update" ON public.client_execution_files FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- MASTER TABLES
CREATE POLICY "om_sel" ON public.organic_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "om_ins" ON public.organic_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "om_upd" ON public.organic_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "om_del" ON public.organic_master FOR DELETE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "sm_sel" ON public.story_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "sm_ins" ON public.story_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "sm_upd" ON public.story_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "sm_del" ON public.story_master FOR DELETE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "am_sel" ON public.ads_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "am_ins" ON public.ads_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "am_upd" ON public.ads_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "am_del" ON public.ads_master FOR DELETE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "ac_sel" ON public.ad_creative FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "ac_ins" ON public.ad_creative FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "ac_upd" ON public.ad_creative FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "pm_sel" ON public.proof_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "pm_ins" ON public.proof_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "pm_upd" ON public.proof_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "asm_sel" ON public.asset_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "asm_ins" ON public.asset_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager', 'editor'));
CREATE POLICY "asm_upd" ON public.asset_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager', 'editor')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager', 'editor'));

CREATE POLICY "lmm_sel" ON public.lead_magnet_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "lmm_ins" ON public.lead_magnet_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "lmm_upd" ON public.lead_magnet_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "wm_sel" ON public.website_master FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "wm_ins" ON public.website_master FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "wm_upd" ON public.website_master FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "sl_sel" ON public.sops_laws FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "sl_ins" ON public.sops_laws FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "sl_upd" ON public.sops_laws FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "ws_sel" ON public.weekly_sequence FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "ws_ins" ON public.weekly_sequence FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "ws_upd" ON public.weekly_sequence FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

CREATE POLICY "abi_sel" ON public.asset_brief_index FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "abi_ins" ON public.asset_brief_index FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "abi_upd" ON public.asset_brief_index FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- CALENDAR
CREATE POLICY "cc_sel" ON public.calendar_cells FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "cc_ins" ON public.calendar_cells FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "cc_upd" ON public.calendar_cells FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "cc_del" ON public.calendar_cells FOR DELETE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager'));

-- PIPELINE
CREATE POLICY "pmd_sel" ON public.pipeline_metrics_daily FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "pmd_ins" ON public.pipeline_metrics_daily FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "pmd_upd" ON public.pipeline_metrics_daily FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- PLAYBOOKS
CREATE POLICY "pb_sel_all"  ON public.playbooks FOR SELECT TO authenticated USING (TRUE);
CREATE POLICY "pb_admin_wr" ON public.playbooks FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- PLAYBOOK RUNS
CREATE POLICY "pbr_sel" ON public.playbook_runs FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "pbr_ins" ON public.playbook_runs FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "pbr_upd" ON public.playbook_runs FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- AUTOMATIONS
CREATE POLICY "auto_sel" ON public.automations FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "auto_ins" ON public.automations FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "auto_upd" ON public.automations FOR UPDATE TO authenticated USING (client_id = ANY(public.auth_client_ids()) AND public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- AUTOMATION RUNS
CREATE POLICY "ar_sel" ON public.automation_runs FOR SELECT TO authenticated USING (client_id = ANY(public.auth_client_ids()));
CREATE POLICY "ar_ins" ON public.automation_runs FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- INTEGRATIONS
CREATE POLICY "int_admin" ON public.integrations FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- SECRET REFERENCES
CREATE POLICY "sr_admin" ON public.secret_references FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- ACTIVITY LOG
CREATE POLICY "al_sel" ON public.activity_log FOR SELECT TO authenticated USING (public.auth_role() IN ('admin', 'account_manager') OR client_id = ANY(public.auth_client_ids()));
CREATE POLICY "al_ins" ON public.activity_log FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- AUDIT LOG
CREATE POLICY "aul_admin" ON public.audit_log FOR ALL TO authenticated USING (public.auth_role() = 'admin') WITH CHECK (public.auth_role() = 'admin');

-- REF COUNTERS
CREATE POLICY "rc_sel" ON public.ref_counters FOR SELECT TO authenticated USING (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "rc_ins" ON public.ref_counters FOR INSERT TO authenticated WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));
CREATE POLICY "rc_upd" ON public.ref_counters FOR UPDATE TO authenticated USING (public.auth_role() IN ('admin', 'account_manager')) WITH CHECK (public.auth_role() IN ('admin', 'account_manager'));

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO public.workspaces (name, slug) VALUES ('Attract Acquisition', 'attract-acquisition') ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.integrations (name, status) VALUES
  ('meta', 'not_configured'), ('openai', 'not_configured'),
  ('apify', 'not_configured'), ('calendly', 'not_configured'),
  ('payfast', 'not_configured'), ('xero', 'not_configured')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.clients (name, slug, is_internal_client, package_tier, status)
VALUES ('Attract Acquisition', 'attract-acquisition', TRUE, 'proof_brand', 'active')
ON CONFLICT (slug) DO NOTHING;
